### ISSUE TITLE
problems with train_dualgpu.py

### ISSUE THREAD

**Issue by Junpink** [baudm/vaegan-celebs-keras#2]
Thank you for your terrific work.
I'm wondering whether the code(train_dualgpu.py) is executable, since several variables do not seem to be defined. ( such as inputs and on outputs on Line 42)

**Comment by baudm** [comment]
You're welcome! Thanks for your interest in our little project. Unfortunately, I wasn't the one who wrote that code so I cannot give any support. I don't think it worked even before. Fortunately, the multi-GPU support of Keras has improved since this project was implemented. Probably only a small modification to `train.py` is needed. For more info, take a look at: https://keras.io/utils/#multi_gpu_model

**Comment by Junpink** [comment]
@baudm I see. thank you for ur response and generosity
